INSERT INTO questions (id, label, age_range, domain) VALUES (1, 'لديه رأس ثابت عندما يجلس', 1, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (2, 'يتبع بنظره الجسم بزاوية 180 درجة', 1, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (3, 'يهز لعبته', 1, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (4, 'يصدر أصواتا', 1, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (5, 'يضحك', 1, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (6, 'يبتسم عند طلب الناس', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (7, 'يتفاعل مع تأثيرات الصوت', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (8, 'يتفاعل مع وصول والدته أو رحيلها', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (9, 'يثبّت بنظراتة نحو أمه', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (10, 'قد يكون مترددًا جدًا في أن يتم احتجازه أو احتضانه أو تقبيله من قبل والديه', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (11, 'قد لا يمد يده عندما ينحني شخص ما ﻹمساكه', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (12, 'هل يعاني طفلك من صعوبة في النوم', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (13, 'هل يعاني طفلك من اضطرابات الأكل', 1, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (14, 'يمكنه الجلوس بدون دعم', 2, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (15, 'يمكن أن يقف مع المساعدة', 2, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (16, 'يمكنه التقاط شيء بيده', 2, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (17, 'يمكن أن يقول مقاطع مثل بابا ماما', 2, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (18, 'هل يتفاعل طفلك مع الضوضاء؟', 2, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (19, 'هل يقوم طفلك بأنشطة فردية : ألعاب الأصابع واليد أمام العينين ، والتأرجح ؟', 2, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (20, 'هل يستخدم طفلك الأشياء بطريقة غير عادية (خدش ، فرك) ؟', 2, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (21, 'هل يظهرطفلك إهتمامه للناس ؟', 2, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (22, 'هل يقوم طفلك بتقليد مفردات وإيماءات والديه ؟', 2, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (23, 'هل يحب طفلك أن يلعب لعبة الخداع أو الاختباء ؟', 2, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (24, 'هل يصبح طفلك قلقاً عندما يكون قريبا من الغرباء في غياب أمه (خوف أن يكون متخلف أو غير نمطي) ؟', 2, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (25, 'اكتسب الطفل المشي قبل سن 1 ونصف', 3, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (26, 'يمكن للطفل أن يتسلق السلالم', 3, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (27, 'يمكن للطفل أن يأخذ شيئا مع مؤشر الإبهام', 3, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (28, 'يمكن للطفل الخربشة بالقلم', 3, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (29, 'يمكن للطفل أن يقول عدة كلمات', 3, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (30, 'هل يبدي طفلك  اهتماماً بأطفال آخرين ؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (31, 'هل يلعب  طفلك  من وقت لآخر ''تظاهر'' على سبيل المثال ,التحدث على الهاتف ، والعناية بالدمى أو أشياء أخرى؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (32, 'هل يستخدم طفلك سبّابته لتصميم أو طلب شيء ما؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (33, 'هل يلعب طفلك بشكل صحيح بألعاب صغيرة (سيارات صغيرة ، كتل..) دون أن يحد من سلوكه لكي يحملها إلى فمه أو يتلاعب بها أو يدعها تسقط ؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (34, 'هل يجلب لك طفلك بانتظام أجساما ليريك شيئًا ما؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (35, 'هل يلفت طفلك انتباهه إلى الشيء الذي تشير إليه؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (36, 'هل لدى طفلك سلوكيات نمطية؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (37, 'هل لطفلك أي اهتمامات معينة (مصادر الضوء ، الأجسام الدوارة)؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (38, 'هل يؤذي طفلك نفسه: يضرب نفسه ، يعض نفسه؟', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (39, 'افتقار اﻹستجابة و التوقع اﻹجتماعي', 3, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (40, 'يقفز في مكانه', 4, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (41, 'يرمي الكرة بيديه', 4, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (42, 'يركل الكرة بقدميه', 4, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (43, 'يستطيع رسم خط مستقيم بعد تعلّمه لذلك', 4, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (44, 'يستطيع تكوين جملة من كلمتين أو أكثر', 4, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (45, 'يسمّي الصورة', 4, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (46, 'يفهم أوامر بسيطة مثل أحضر حذائك', 4, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (47, 'يجري', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (48, 'يصعد الدرج دون مساعدة', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (49, 'يقود دراجة ثلاثية العجلات', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (50, ' يرمي الكرة بيديه', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (51, 'يركل الكرة بقدميه', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (52, 'يفتح و يغلق الزجاجة', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (53, 'يستخدم الملعقة بشكل صحيح', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (54, 'يخلع ملابسه وحده دون مساعدة', 5, 1);
INSERT INTO questions (id, label, age_range, domain) VALUES (55, 'يستدير عندما ينادى باسمه الأول', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (56, 'يتكلم عند طلب اسمه و لقبه', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (57, 'غالبًا ما يستخدم جمل من كلمتين أو ثلاث للتعبير عن نفسه مثل: ''بابا أخذ الكرة'' ويطرح أسئلة مثل ''أين ماما؟''', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (58, 'عادة ما يلفظ عدة أصوات بشكل صحيح', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (59, 'واضح مع الغرباء', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (60, 'يفهم التعليمات من خلال ثلاثة إجراءات متتالية ، مثال :اخلع حذائك ، اختر كتابًا ، ثم اجلس', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (61, 'يفهم التعليمات التي تتضمن مفاهيم أكثر تعقيدًا ، على سبيل المثال المصطلحات المتعلقة بالمكان أو الزمان ، مثل ''ضع معطفك بجوار الكرسي الكبير'' ,او ''اغسل أسنانك بالفرشاة. بعد ذلك سنقرأ قصة''', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (62, 'يعيّن صورة بالإشارة', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (63, 'يستعمل الضمير أنا', 5, 2);
INSERT INTO questions (id, label, age_range, domain) VALUES (64, 'يتواصل مع عائلته', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (65, 'يتواصل مع بيئته التعليمية', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (66, 'يبدي الرفض باستعمال ''لا''', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (67, 'يحب التقليد(يعد وجبه,يرفع سماعة الهاتف, تقليد سلوك الكبار)', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (68, 'يمكن أن يخلق صديقًا خياليّا', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (69, 'يشارك في الأنشطة المنزلية للبالغين (تحضير الطاولة ، وترك الوسائد ، وما إلى ذلك)', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (70, 'يقبل بعض الحدود', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (71, 'يتحكم في فضلاته', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (72, 'يتحكم في المجاري البولية', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (73, 'يكتشف الفرق الجنسي بين الفتاة والصبي', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (74, 'يتناوب مع الأطفال الآخرين(ينتظر دوره)', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (75, 'البحث عن أطفال للمشاركة في الألعاب', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (76, 'يلعب بالألعاب المتاحة', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (77, 'يخاف من الّيل', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (78, 'يتذمر عدة مرات', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (79, 'متعلق جدا بوالدته', 5, 3);
INSERT INTO questions (id, label, age_range, domain) VALUES (80, 'بدأ بمعرفة الألوان (أصفر ، أحمر ، أخضر)', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (81, 'بدأ في معرفة الأشكال (الدائرة)', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (82, 'يعد حتى 5', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (83, 'لديه فكرة الكمية تصل إلى 2', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (84, 'يمكنه فهم الاختلاف بين شيء واحد أو أشياء كثيرة', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (85, 'عند الطلب ،يمكنه تحديد الشيء اذا كان كبيرا أو صغيرا', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (86, 'يفهم فائدة الأشياء المستعملة يوميا (الغاز لتحضير الوجبة ...)', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (87, 'ينسخ  خط أو دائرة', 5, 4);
INSERT INTO questions (id, label, age_range, domain) VALUES (88, 'يعرف المفاهيم المكانية مثل ''في'' ، ''على'' ، ''فوق'' ، ''أدناه''', 5, 4);