INSERT INTO questions (id, age_range, domain, label) VALUES (1, 1, 1, 'لديه رأس ثابت عندما يجلس');
INSERT INTO questions (id, age_range, domain, label) VALUES (2, 1, 1, 'يتبع بنظره الجسم بزاوية 180 درجة');
INSERT INTO questions (id, age_range, domain, label) VALUES (3, 1, 1, 'يهز لعبته');
INSERT INTO questions (id, age_range, domain, label) VALUES (4, 1, 2, 'يصدر أصواتا');
INSERT INTO questions (id, age_range, domain, label) VALUES (5, 1, 2, 'يضحك');
INSERT INTO questions (id, age_range, domain, label) VALUES (6, 1, 3, 'يبتسم عند طلب الناس');
INSERT INTO questions (id, age_range, domain, label) VALUES (7, 1, 3, 'يتفاعل مع تأثيرات الصوت');
INSERT INTO questions (id, age_range, domain, label) VALUES (8, 1, 3, 'يتفاعل مع وصول والدته أو رحيلها');
INSERT INTO questions (id, age_range, domain, label) VALUES (9, 1, 3, 'يثبّت بنظراتة نحو أمه');
INSERT INTO questions (id, age_range, domain, label) VALUES (10, 1, 3, 'قد يكون مترددًا جدًا في أن يتم احتجازه أو احتضانه أو تقبيله من قبل والديه');
INSERT INTO questions (id, age_range, domain, label) VALUES (11, 1, 3, 'قد لا يمد يده عندما ينحني شخص ما ﻹمساكه');
INSERT INTO questions (id, age_range, domain, label) VALUES (12, 1, 3, 'هل يعاني طفلك من صعوبة في النوم');
INSERT INTO questions (id, age_range, domain, label) VALUES (13, 1, 3, 'هل يعاني طفلك من اضطرابات الأكل');
INSERT INTO questions (id, age_range, domain, label) VALUES (14, 2, 1, 'يمكنه الجلوس بدون دعم');
INSERT INTO questions (id, age_range, domain, label) VALUES (15, 2, 1, 'يمكن أن يقف مع المساعدة');
INSERT INTO questions (id, age_range, domain, label) VALUES (16, 2, 1, 'يمكنه التقاط شيء بيده');
INSERT INTO questions (id, age_range, domain, label) VALUES (17, 2, 2, 'يمكن أن يقول مقاطع مثل بابا ماما');
INSERT INTO questions (id, age_range, domain, label) VALUES (18, 2, 3, 'هل يتفاعل طفلك مع الضوضاء؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (19, 2, 3, 'هل يقوم طفلك بأنشطة فردية : ألعاب الأصابع واليد أمام العينين ، والتأرجح ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (20, 2, 3, 'هل يستخدم طفلك الأشياء بطريقة غير عادية (خدش ، فرك) ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (21, 2, 3, 'هل يظهرطفلك إهتمامه للناس ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (22, 2, 3, 'هل يقوم طفلك بتقليد مفردات وإيماءات والديه ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (23, 2, 3, 'هل يحب طفلك أن يلعب لعبة الخداع أو الاختباء ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (24, 2, 3, 'هل يصبح طفلك قلقاً عندما يكون قريبا من الغرباء في غياب أمه (خوف أن يكون متخلف أو غير نمطي) ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (25, 3, 1, 'اكتسب الطفل المشي قبل سن 1 ونصف');
INSERT INTO questions (id, age_range, domain, label) VALUES (26, 3, 1, 'يمكن للطفل أن يتسلق السلالم');
INSERT INTO questions (id, age_range, domain, label) VALUES (27, 3, 1, 'يمكن للطفل أن يأخذ شيئا مع مؤشر الإبهام');
INSERT INTO questions (id, age_range, domain, label) VALUES (28, 3, 1, 'يمكن للطفل الخربشة بالقلم');
INSERT INTO questions (id, age_range, domain, label) VALUES (29, 3, 2, 'يمكن للطفل أن يقول عدة كلمات');
INSERT INTO questions (id, age_range, domain, label) VALUES (30, 3, 3, 'هل يبدي طفلك  اهتماماً بأطفال آخرين ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (31, 3, 3, 'هل يلعب  طفلك  من وقت لآخر ''تظاهر'' على سبيل المثال ,التحدث على الهاتف ، والعناية بالدمى أو أشياء أخرى؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (32, 3, 3, 'هل يستخدم طفلك سبّابته لتصميم أو طلب شيء ما؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (33, 3, 3, 'هل يلعب طفلك بشكل صحيح بألعاب صغيرة (سيارات صغيرة ، كتل..) دون أن يحد من سلوكه لكي يحملها إلى فمه أو يتلاعب بها أو يدعها تسقط ؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (34, 3, 3, 'هل يجلب لك طفلك بانتظام أجساما ليريك شيئًا ما؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (35, 3, 3, 'هل يلفت طفلك انتباهه إلى الشيء الذي تشير إليه؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (36, 3, 3, 'هل لدى طفلك سلوكيات نمطية؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (37, 3, 3, 'هل لطفلك أي اهتمامات معينة (مصادر الضوء ، الأجسام الدوارة)؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (38, 3, 3, 'هل يؤذي طفلك نفسه: يضرب نفسه ، يعض ​​نفسه؟');
INSERT INTO questions (id, age_range, domain, label) VALUES (39, 3, 3, 'افتقار اﻹستجابة و التوقع اﻹجتماعي');
INSERT INTO questions (id, age_range, domain, label) VALUES (40, 4, 1, 'يقفز في مكانه');
INSERT INTO questions (id, age_range, domain, label) VALUES (41, 4, 1, 'يرمي الكرة بيديه');
INSERT INTO questions (id, age_range, domain, label) VALUES (42, 4, 1, 'يركل الكرة بقدميه');
INSERT INTO questions (id, age_range, domain, label) VALUES (43, 4, 1, 'يستطيع رسم خط مستقيم بعد تعلّمه لذلك');
INSERT INTO questions (id, age_range, domain, label) VALUES (44, 4, 2, 'يستطيع تكوين جملة من كلمتين أو أكثر');
INSERT INTO questions (id, age_range, domain, label) VALUES (45, 4, 2, 'يسمّي الصورة');
INSERT INTO questions (id, age_range, domain, label) VALUES (46, 4, 2, 'يفهم أوامر بسيطة مثل أحضر حذائك');
INSERT INTO questions (id, age_range, domain, label) VALUES (47, 5, 1, 'يجري');
INSERT INTO questions (id, age_range, domain, label) VALUES (48, 5, 1, 'يصعد الدرج دون مساعدة');
INSERT INTO questions (id, age_range, domain, label) VALUES (49, 5, 1, 'يقود دراجة ثلاثية العجلات');
INSERT INTO questions (id, age_range, domain, label) VALUES (50, 5, 1, ' يرمي الكرة بيديه');
INSERT INTO questions (id, age_range, domain, label) VALUES (51, 5, 1, 'يركل الكرة بقدميه');
INSERT INTO questions (id, age_range, domain, label) VALUES (52, 5, 1, 'يفتح و يغلق الزجاجة');
INSERT INTO questions (id, age_range, domain, label) VALUES (53, 5, 1, 'يستخدم الملعقة بشكل صحيح');
INSERT INTO questions (id, age_range, domain, label) VALUES (54, 5, 1, 'يخلع ملابسه وحده دون مساعدة');
INSERT INTO questions (id, age_range, domain, label) VALUES (55, 5, 2, 'يستدير عندما ينادى باسمه الأول');
INSERT INTO questions (id, age_range, domain, label) VALUES (56, 5, 2, 'يتكلم عند طلب اسمه و لقبه');
INSERT INTO questions (id, age_range, domain, label) VALUES (57, 5, 2, 'غالبًا ما يستخدم جمل من كلمتين أو ثلاث للتعبير عن نفسه مثل: ''بابا أخذ الكرة'' ويطرح أسئلة مثل ''أين ماما؟''');
INSERT INTO questions (id, age_range, domain, label) VALUES (58, 5, 2, 'عادة ما يلفظ عدة أصوات بشكل صحيح');
INSERT INTO questions (id, age_range, domain, label) VALUES (59, 5, 2, 'واضح مع الغرباء');
INSERT INTO questions (id, age_range, domain, label) VALUES (60, 5, 2, 'يفهم التعليمات من خلال ثلاثة إجراءات متتالية ، مثال :اخلع حذائك ، اختر كتابًا ، ثم اجلس');
INSERT INTO questions (id, age_range, domain, label) VALUES (61, 5, 2, 'يفهم التعليمات التي تتضمن مفاهيم أكثر تعقيدًا ، على سبيل المثال المصطلحات المتعلقة بالمكان أو الزمان ، مثل ''ضع معطفك بجوار الكرسي الكبير'' ,او ''اغسل أسنانك بالفرشاة. بعد ذلك سنقرأ قصة''');
INSERT INTO questions (id, age_range, domain, label) VALUES (62, 5, 2, 'يعيّن صورة بالإشارة');
INSERT INTO questions (id, age_range, domain, label) VALUES (63, 5, 2, 'يستعمل الضمير أنا');
INSERT INTO questions (id, age_range, domain, label) VALUES (64, 5, 3, 'يتواصل مع عائلته');
INSERT INTO questions (id, age_range, domain, label) VALUES (65, 5, 3, 'يتواصل مع بيئته التعليمية');
INSERT INTO questions (id, age_range, domain, label) VALUES (66, 5, 3, 'يبدي الرفض باستعمال ''لا''');
INSERT INTO questions (id, age_range, domain, label) VALUES (67, 5, 3, 'يحب التقليد(يعد وجبه,يرفع سماعة الهاتف, تقليد سلوك الكبار)');
INSERT INTO questions (id, age_range, domain, label) VALUES (68, 5, 3, 'يمكن أن يخلق صديقًا خياليّا');
INSERT INTO questions (id, age_range, domain, label) VALUES (69, 5, 3, 'يشارك في الأنشطة المنزلية للبالغين (تحضير الطاولة ، وترك الوسائد ، وما إلى ذلك)');
INSERT INTO questions (id, age_range, domain, label) VALUES (70, 5, 3, 'يقبل بعض الحدود');
INSERT INTO questions (id, age_range, domain, label) VALUES (71, 5, 3, 'يتحكم في فضلاته');
INSERT INTO questions (id, age_range, domain, label) VALUES (72, 5, 3, 'يتحكم في المجاري البولية');
INSERT INTO questions (id, age_range, domain, label) VALUES (73, 5, 3, 'يكتشف الفرق الجنسي بين الفتاة والصبي');
INSERT INTO questions (id, age_range, domain, label) VALUES (74, 5, 3, 'يتناوب مع الأطفال الآخرين(ينتظر دوره)');
INSERT INTO questions (id, age_range, domain, label) VALUES (75, 5, 3, 'البحث عن أطفال للمشاركة في الألعاب');
INSERT INTO questions (id, age_range, domain, label) VALUES (76, 5, 3, 'يلعب بالألعاب المتاحة');
INSERT INTO questions (id, age_range, domain, label) VALUES (77, 5, 3, 'يخاف من الّيل');
INSERT INTO questions (id, age_range, domain, label) VALUES (78, 5, 3, 'يتذمر عدة مرات');
INSERT INTO questions (id, age_range, domain, label) VALUES (79, 5, 3, 'متعلق جدا بوالدته');
INSERT INTO questions (id, age_range, domain, label) VALUES (80, 5, 4, 'بدأ بمعرفة الألوان (أصفر ، أحمر ، أخضر)');
INSERT INTO questions (id, age_range, domain, label) VALUES (81, 5, 4, 'بدأ في معرفة الأشكال (الدائرة)');
INSERT INTO questions (id, age_range, domain, label) VALUES (82, 5, 4, 'يعد حتى 5');